import { React } from 'react';
import Footer from './Footer';
import Header from './Header';

function Service() {
    return (
        <div className='bg-cokelat'>
            <Header />
            <div className='px-24 py-10 text-white text-justify'>
                <h2 className='font-dosis text-center font-bold text-5xl'>Terms Of Service</h2>
                <h5 className='font-dosis font-bold text-xl pt-5'>License Grant and Restrictions</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>Accessing the Bloomers Platform</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>Using the Bloomers Platform</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>Subscription Services</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>Payments</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>Cancellation and Refunds</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>

                <h5 className='font-dosis font-bold text-xl pt-5'>User Reviews, Social Feed, Comments and Other Material</h5>
                <p className='font-esteban'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo nec ultrices dui sapien eget mi. Risus pretium quam vulputate dignissim suspendisse in est. Scelerisque felis imperdiet proin fermentum leo vel orci. Vestibulum rhoncus est pellentesque elit. Enim sed faucibus turpis in eu. Consequat interdum varius sit amet mattis vulputate. Leo urna molestie at elementum eu facilisis sed odio morbi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet nisl purus in mollis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Ornare lectus sit amet est placerat in egestas erat. Tempus iaculis urna id volutpat. Velit euismod in pellentesque massa. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Lectus vestibulum mattis ullamcorper velit. Non quam lacus suspendisse faucibus interdum posuere.</p>
            </div>
            <Footer />
        </div>
    );
}

export default Service;